### ISSUE TITLE
Parcel build error while importing custom tfjs build from this repo

### ISSUE THREAD

**Issue by Shandelier** [vladmandic/tfjs#2]
Bundling my app with Parcel results in error:

<details>
  <summary>yarn run build: error message</summary>
  
  ```
  🚨 Build failed.

@parcel/core: Failed to resolve '@vladmandic/tfjs' from './src/background.js'

  /home/wespazjan/dev/Sit-Stand-Right-Extension/src/background.js:294:21
    293 |
  > 294 | import * as tf from '@vladmandic/tfjs'
  >     |                     ^^^^^^^^^^^^^^^^^^
    295 | console.log(tf)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
  ```
  
</details>

my ```package.json``` file looks like this:

```json
{
"name": "Sit_Stand_Right",
  "version": "0.1.0",
  "description": "gentle reminder of healthy posture!",
  "scripts": {
    "clean": "rm -rf dist/*",
    "reset": "rm -rf node_modules/ && npm i",
    "copy": "rsync -aq src/content.js dist/src/ && rsync -aq src/css/* dist/src/css && rsync -aq manifest.json dist/ && rsync -aq src/icons/* dist/src/icons/",
    "build": "cross-env NODE_ENV=production yarn clean && parcel build src/background.js --dist-dir dist/src/ && npm run copy",
    "watch": "npm run copy && parcel watch src/background.js --dist-dir dist/src/"
  },
  "license": "Apache 2.0",
  "dependencies": {
    "@mediapipe/pose": "~0.4.0",
    "@tensorflow-models/pose-detection": "file:../tfjs-models/pose-detection/dist",
  },
  "devDependencies": {
    "@babel/core": "^7.7.5",
    "@babel/plugin-transform-runtime": "^7.7.6",
    "@babel/preset-env": "^7.7.6",
    "babel-plugin-external-helpers": "^6.22.0",
    "babel-preset-env": "^1.7.0",
    "clang-format": "~1.2.2",
    "cross-env": "^5.2.0",
    "eslint": "^7.2.0",
    "eslint-config-google": "^0.14.0",
    "parcel": "^2.0.0",
    "parcel-plugin-static-files-copy": "^2.5.1",
    "yalc": "~1.0.0-pre.50"
  }
}
```

I'm trying to use tfjs in the file ```background.js```:
```javascript
import * as tf from '@vladmandic/tfjs'
console.log(tf)
``` 

the ```@tensorflow-models/pose-detection``` dependency also is build locally but it's working correct.

I'm not sure if I'm using correctly files from ```dist/``` from this repo as a dependency in my project. I will be grateful for any help!

**Comment by vladmandic** [comment]
> @parcel/core: Failed to resolve '@vladmandic/tfjs' from './src/background.js'  

i don't see `@vladmandic/tfjs` in your `package.json` dependencies, so of course it failed to resolve?  

even if its build locally, you still want to include it so it can be resolved  

for example, if i have `@vladmandic/tfjs` cloned and build in a relative path `../tfjs`,  
then running `npm install ../tfjs` creates entry in `package.json`:  
> "@vladmandic/tfjs": "file:../tfjs"

and if you look inside `@vladmandic/tfjs/package.json`, you'll see:  
>   "module": "dist/tfjs.esm.js",

so parcel would then be able to resolve `import * as tf from '@vladmandic/tfjs'` to `../tfjs/dist/tfjs.esm.js`

**Comment by Shandelier** [comment]
Thanks for the answer! 
My mistake was trying to manually provide the path to .js files of compiled dependency and not the `package.json`. Now it's working!
