### ISSUE TITLE
link: -> file: in package.json

### ISSUE THREAD

**Issue by bengower** [vladmandic/tfjs#4]
Hello,

For compatibility with newer npm versions:

you might want to change:

"dependencies": {
    "@tensorflow/tfjs-core": "link:src/tfjs-core",
    "@tensorflow/tfjs-data": "link:src/tfjs-data",
    "@tensorflow/tfjs-layers": "link:src/tfjs-layers",
    "@tensorflow/tfjs-converter": "link:src/tfjs-converter",
    "@tensorflow/tfjs-backend-cpu": "link:src/tfjs-backend-cpu",
    "@tensorflow/tfjs-backend-wasm": "link:src/tfjs-backend-wasm",
    "@tensorflow/tfjs-backend-webgl": "link:src/tfjs-backend-webgl",
    "@tensorflow/tfjs-backend-webgpu": "link:src/tfjs-backend-webgpu"
  }

to:

"dependencies": {
    "@tensorflow/tfjs-core": "file:src/tfjs-core",
    "@tensorflow/tfjs-data": "file:src/tfjs-data",
    "@tensorflow/tfjs-layers": "file:src/tfjs-layers",
    "@tensorflow/tfjs-converter": "file:src/tfjs-converter",
    "@tensorflow/tfjs-backend-cpu": "file:src/tfjs-backend-cpu",
    "@tensorflow/tfjs-backend-wasm": "file:src/tfjs-backend-wasm",
    "@tensorflow/tfjs-backend-webgl": "file:src/tfjs-backend-webgl",
    "@tensorflow/tfjs-backend-webgpu": "file:src/tfjs-backend-webgpu"
  }

**Comment by vladmandic** [comment]
i'll check if its cross-tool as i use `pnpm` by default.

**Comment by vladmandic** [comment]
done.
